#!/bin/bash

source $(dirname $0)/../util/print.sh

source $(dirname $0)/../asset/icon.sh

source $(dirname $0)/../style/color.sh

MESSAGE=`head -n 1 "$1"`
MAX_LENGTH=80
TYPE_ERROR=0
PATTERN="([a-z:]) ([a-z]+)(\(.*\))?: (^[a-z]+)$"
COMMIT_TYPES=(
':sparkles: feat'
':bug: fix'
':fire: remove'
':memo: doc'
':art: style'
':recycle: refactor'
':zap: perf'
':test_tube: test'
':construction_worker: ci'
':rocket: release'
':rotating_light: breaking'
':wrench: config'
':lock: security'
':globe_with_meridians: language'
':tada: begin'
':pencil2: typo'
':bento: asset'
':package: package')

if [[ ${#MESSAGE} > $MAX_LENGTH ]]; then
  print_error "Commit message was ${#MESSAGE} characters long, but should be at most $MAX_LENGTH characters"
  exit 1
fi

if ! [[ "$MESSAGE" =~ $PATTERN ]]; then
  print_error "Commit message did not match 'icon type(scope): subject'"
fi

for VALUE in "${COMMIT_TYPES[@]}"; do

  if [[ $MESSAGE == *$VALUE* ]]; then
    TYPE_ERROR=0
    break
  fi

  TYPE_ERROR=1
done

if [[ $TYPE_ERROR == 1 ]]; then
  print_error "Commit message's type must be one of:"
  echo -e "$COMMIT_ICONS"
  exit 1
fi

print_success "Commit successfully"