#!/bin/bash

source $(dirname $0)/../module/eslint.sh

source $(dirname $0)/../util/add_files_to_staged_tree.sh
source $(dirname $0)/../util/create_pattern.sh
source $(dirname $0)/../util/filter_array_with_inverted_regex.sh
source $(dirname $0)/../util/prepare_staged_files.sh
source $(dirname $0)/../util/print.sh
source $(dirname $0)/../util/remove_last_char.sh
source $(dirname $0)/../util/spinner.sh

source $(dirname $0)/../asset/icon.sh

source $(dirname $0)/../style/color.sh

printf "\n"

eslint_hook
