import { bestPractice } from '../../eslint/rule/best_practice';
import { error } from '../../eslint/rule/error';
import { style } from '../../eslint/rule/style';

const typescriptStyle =
{
  '@typescript-eslint/adjacent-overload-signatures': 'error',
  '@typescript-eslint/block-spacing': style['block-spacing'],
  '@typescript-eslint/brace-style': style['brace-style'],
  '@typescript-eslint/comma-dangle': style['comma-dangle'],
  '@typescript-eslint/comma-spacing': style['comma-spacing'],
  '@typescript-eslint/default-param-last': bestPractice['default-param-last'],
  '@typescript-eslint/dot-notation': style['dot-notation'],
  '@typescript-eslint/func-call-spacing': style['func-call-spacing'],
  '@typescript-eslint/indent': style.indent,
  '@typescript-eslint/init-declarations': bestPractice['init-declarations'],
  '@typescript-eslint/key-spacing': style['key-spacing'],
  '@typescript-eslint/lines-between-class-members': style['lines-between-class-members'],
  '@typescript-eslint/no-array-constructor': error['no-array-constructor'],
  '@typescript-eslint/no-dupe-class-members': error['no-dupe-class-members'],
  '@typescript-eslint/no-empty-function': error['no-empty-function'],
  '@typescript-eslint/no-extra-parens': style['no-extra-parens'],
  '@typescript-eslint/no-extra-semi': error['no-extra-semi'],
  '@typescript-eslint/no-implied-eval': error['no-implied-eval'],
  '@typescript-eslint/no-invalid-this': error['no-invalid-this'],
  '@typescript-eslint/no-loop-func': error['no-loop-func'],
  '@typescript-eslint/no-loss-of-precision': error['no-loss-of-precision'],
  '@typescript-eslint/no-magic-numbers': error['no-magic-numbers'],
  '@typescript-eslint/no-redeclare': error['no-redeclare'],
  '@typescript-eslint/no-restricted-imports': error['no-restricted-imports'],
  '@typescript-eslint/no-shadow': error['no-shadow'],
  '@typescript-eslint/no-throw-literal': error['no-throw-literal'],
  '@typescript-eslint/no-unused-expressions': error['no-unused-expressions'],
  '@typescript-eslint/no-unused-vars': error['no-unused-vars'],
  '@typescript-eslint/no-use-before-define': error['no-use-before-define'],
  '@typescript-eslint/no-useless-constructor': error['no-useless-constructor'],
  '@typescript-eslint/object-curly-spacing': style['object-curly-spacing'],
  '@typescript-eslint/padding-line-between-statements': style['padding-line-between-statements'],
  '@typescript-eslint/quotes': style.quotes,
  '@typescript-eslint/require-await': bestPractice['require-await'],
  '@typescript-eslint/return-await': error['no-return-await'],
  '@typescript-eslint/semi': style.semi,
  '@typescript-eslint/space-before-blocks': style['space-before-blocks'],
  '@typescript-eslint/space-before-function-paren': style['space-before-function-paren'],
  '@typescript-eslint/space-infix-ops': style['space-infix-ops'],
  'block-spacing': 'off',
  'brace-style': 'off',
  'comma-dangle': 'off',
  'comma-spacing': 'off',
  'default-param-last': 'off',
  'dot-notation': 'off',
  'func-call-spacing': 'off',
  indent: 'off',
  'init-declarations': 'off',
  'key-spacing': 'off',
  'lines-between-class-members': 'off',
  'no-array-constructor': 'off',
  'no-dupe-class-members': 'off',
  'no-empty-function': 'off',
  'no-extra-parens': 'off',
  'no-extra-semi': 'off',
  'no-implied-eval': 'off',
  'no-invalid-this': 'off',
  'no-loop-func': 'off',
  'no-loss-of-precision': 'off',
  'no-magic-numbers': 'off',
  'no-redeclare': 'off',
  'no-restricted-imports': 'off',
  'no-return-await': 'off',
  'no-shadow': 'off',
  'no-throw-literal': 'off',
  'no-unused-expressions': 'off',
  'no-unused-vars': 'off',
  'no-use-before-define': 'off',
  'no-useless-constructor': 'off',
  'object-curly-spacing': 'off',
  'padding-line-between-statements': 'off',
  quotes: 'off',
  'require-await': 'off',
  semi: 'off',
  'space-before-blocks': 'off',
  'space-before-function-paren': 'off',
  'space-infix-ops': 'off'
};

export { typescriptStyle };